#############################################################################
# Makefile for building: build/debug/parallelngsa2
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  ParallelNSGAII.pro
# Template: app
# Command: /Users/calebbuahin/Qt5.7.0/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ParallelNSGAII.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /usr/local/bin/mpicc
CXX           = /usr/local/bin/mpic++
DEFINES       = -DUSE_MPI -DQT_QML_DEBUG
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12.6 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12.6 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include -I../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang
QMAKE         = /Users/calebbuahin/Qt5.7.0/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = parallelngsa21.1
DISTDIR = /Users/calebbuahin/Documents/Projects/HydroCouple/ParallelNSGAII/build/debug/.obj/parallelngsa21.1
LINK          = /usr/local/bin/mpic++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12.6
LIBS          = $(SUBLIBS) -L/usr/local/lib/ -lmpi 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = allocate.c \
		auxiliary.c \
		crossover.c \
		crowddist.c \
		decode.c \
		dominance.c \
		fillnds.c \
		initialize.c \
		list.c \
		merge.c \
		mutation.c \
		rand.c \
		rank.c \
		report.c \
		sort.c \
		tourselect.c \
		eval.cpp \
		problemdef.cpp \
		parallelnsga2r.cpp 
OBJECTS       = build/debug/.obj/allocate.o \
		build/debug/.obj/auxiliary.o \
		build/debug/.obj/crossover.o \
		build/debug/.obj/crowddist.o \
		build/debug/.obj/decode.o \
		build/debug/.obj/dominance.o \
		build/debug/.obj/fillnds.o \
		build/debug/.obj/initialize.o \
		build/debug/.obj/list.o \
		build/debug/.obj/merge.o \
		build/debug/.obj/mutation.o \
		build/debug/.obj/rand.o \
		build/debug/.obj/rank.o \
		build/debug/.obj/report.o \
		build/debug/.obj/sort.o \
		build/debug/.obj/tourselect.o \
		build/debug/.obj/eval.o \
		build/debug/.obj/problemdef.o \
		build/debug/.obj/parallelnsga2r.o
DIST          = ../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		ParallelNSGAII.pro global.h \
		rand.h \
		problemdef.h allocate.c \
		auxiliary.c \
		crossover.c \
		crowddist.c \
		decode.c \
		dominance.c \
		fillnds.c \
		initialize.c \
		list.c \
		merge.c \
		mutation.c \
		rand.c \
		rank.c \
		report.c \
		sort.c \
		tourselect.c \
		eval.cpp \
		problemdef.cpp \
		parallelnsga2r.cpp
QMAKE_TARGET  = parallelngsa2
DESTDIR       = build/debug/
TARGET        = build/debug/parallelngsa2


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d build/debug/ || mkdir -p build/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ParallelNSGAII.pro ../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		ParallelNSGAII.pro
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ParallelNSGAII.pro
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf:
ParallelNSGAII.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ParallelNSGAII.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/debug/.obj/allocate.o: allocate.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/allocate.o allocate.c

build/debug/.obj/auxiliary.o: auxiliary.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/auxiliary.o auxiliary.c

build/debug/.obj/crossover.o: crossover.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/crossover.o crossover.c

build/debug/.obj/crowddist.o: crowddist.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/crowddist.o crowddist.c

build/debug/.obj/decode.o: decode.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/decode.o decode.c

build/debug/.obj/dominance.o: dominance.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/dominance.o dominance.c

build/debug/.obj/fillnds.o: fillnds.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/fillnds.o fillnds.c

build/debug/.obj/initialize.o: initialize.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/initialize.o initialize.c

build/debug/.obj/list.o: list.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/list.o list.c

build/debug/.obj/merge.o: merge.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/merge.o merge.c

build/debug/.obj/mutation.o: mutation.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/mutation.o mutation.c

build/debug/.obj/rand.o: rand.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/rand.o rand.c

build/debug/.obj/rank.o: rank.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/rank.o rank.c

build/debug/.obj/report.o: report.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/report.o report.c

build/debug/.obj/sort.o: sort.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/sort.o sort.c

build/debug/.obj/tourselect.o: tourselect.c global.h \
		rand.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/tourselect.o tourselect.c

build/debug/.obj/eval.o: eval.cpp rand.h \
		problemdef.h \
		global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/eval.o eval.cpp

build/debug/.obj/problemdef.o: problemdef.cpp problemdef.h \
		global.h \
		rand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/problemdef.o problemdef.cpp

build/debug/.obj/parallelnsga2r.o: parallelnsga2r.cpp global.h \
		rand.h \
		problemdef.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/parallelnsga2r.o parallelnsga2r.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

